___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]   # a normal python list
my_list

In [ ]:
np.array(my_list)   # casting a normal python 1D list into a vector, deonoted by the sinfle set of square brackets

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]   # a normal python list of lists / 2D python list
my_matrix

In [ ]:
np.array(my_matrix) # cast a 2D python list into a matrix (2D numpy array), denoted by the 2 sets of square brackets

# Built-in Methods

There are lots of built-in ways to generate Arrays, more efficiently than the above methods:

### ARANGE()

Return evenly spaced values within a given interval. Similar to the python range(start, stop, step)

In [ ]:
np.arange(0,9)  # Works similar to range()

In [ ]:
np.arange(0,11,2)   # with a step value

### ZEROS() & ONES()

Generate arrays of zeros or ones

In [ ]:
np.zeros(5) # Creates a 1D array of zeros i.e 1 row

In [ ]:
np.zeros((4,3)) # Creates a 2D array of zeros i.e (5 rows, 5 colums). Note the arg for 2D array must be a tuple

In [ ]:
np.ones(3)  # Works the same as the zeros method.

In [ ]:
np.ones((3,3))

### LINSPACE()
Return a vector of evenly spaced numbers over a specified interval.

In [3]:
np.linspace(0,10,3) # Return 3 evenly spaced numbers between 0 and 10

array([ 0.,  5., 10.])

In [ ]:
np.linspace(2,9,100) # Return 100 evenly spaced numbers between 2 and 9

In [ ]:
np.linspace(0,1,50) # Return 50 evenly spaced numbers between 0 and 1

## EYE()

Creates an identity matrix (a square matrix with every element in the leading diagonal having 1s and all other elements having zeros) with the number of rows and columns equal to the argument passed to it.

In [ ]:
np.eye(3)

## RANDOM

Numpy also has lots of ways to create random number arrays:

### RAND()

Creates an array (either vector or matrix) of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``.

In [11]:
np.random.rand(4)   # Create a 4-element vector

array([0.42586216, 0.60442502, 0.86176808, 0.16646982])

In [13]:
np.random.rand(5,5) # Create a 5*5 matrix

array([[0.99797915, 0.90684106, 0.41344994, 0.5425321 , 0.35356921],
       [0.95152609, 0.77298314, 0.09049225, 0.33358195, 0.79717904],
       [0.85437682, 0.95311177, 0.14798815, 0.85972898, 0.97625896],
       [0.03289228, 0.04665784, 0.10409884, 0.24601358, 0.83186704],
       [0.53680687, 0.25615491, 0.73120395, 0.30730306, 0.69461883]])

### RANDN()

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [133]:
np.random.randn(2)

array([ 0.6666141 , -0.08127002])

In [132]:
### RANF()
np.random.ranf(5)

array([0.05106926, 0.35077394, 0.01928652, 0.8960851 , 0.50707972])

In [45]:
np.random.randn(5,5)

array([[-0.63398383,  0.12752627,  0.86265047,  1.1917496 ,  1.28524038],
       [-0.60202596,  0.55685452,  1.58558728, -1.36570752, -0.68564775],
       [-0.39070413,  0.70550634,  0.40165471,  0.69589813,  1.22846914],
       [-1.54228171,  0.18279796,  0.41556946, -0.44323024, -1.79728187],
       [-0.38312054, -0.31508959, -1.19834276,  0.41003739,  0.38164745]])

In [ ]:
### RANDINT()
Return random integers from `low` (inclusive) to `high` (exclusive) i.e 'low' has a higher chance of selection if 'high' is not included.

In [130]:
np.random.randint(1,100) # returns one random integer between 1 and 100

60

In [50]:
np.random.randint(1,100,10) # returns a vector of 10 random integer between 1 and 100

array([25, 64, 80, 73, 75, 44, 62, 45, 30,  9])

# Array Attributes and Methods

In [15]:
arr = np.arange(25) # create a vector of 25 elements between 0 - 24
ranarr = np.random.randint(0,50,9) # create a vector of 10 random elements between 0 and 50

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ranarr

array([26, 39,  1,  0,  5, 33,  4, 24, 36])

## RESHAPE()
Returns an array containing the same data with a new shape. Note the number of elements in the input must be enough to exacly build the new shape else a ValueError execption will be raised, NO MORE, NO LESS.

In [18]:
arr.reshape(5,5)    # Since arr has 25 elements, these are enough to create a 5*5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr.reshape(6,5)    # Raises ValueError

ValueError: cannot reshape array of size 25 into shape (6,5)

In [20]:
arr.reshape(4,4)   # Raises ValueError

ValueError: cannot reshape array of size 25 into shape (4,4)

### MAX(), MIN(), ARGMAX(), ARGMIN()

These are useful methods for finding max() or min() values in an array, or to find their index locations using argmin() or argmax()

In [22]:
rarray = ranarr.reshape(3,3)
rarray

array([[26, 39,  1],
       [ 0,  5, 33],
       [ 4, 24, 36]])

In [23]:
rarray.max()

39

In [24]:
rarray.argmax()

1

In [26]:
rarray.min()

0

In [28]:
rarray.argmin()

3

## SHAPE

Shape is an array ATTRIBUTE (not a method), which returns the shape of the array

In [3]:
t_arry = np.random.rand(5,5)
t_arry

array([[0.68604398, 0.48760717, 0.91450232, 0.50920939, 0.55626204],
       [0.03008223, 0.31888678, 0.42574807, 0.26249342, 0.83257085],
       [0.76911744, 0.12980691, 0.41680284, 0.75819428, 0.60237452],
       [0.48123654, 0.59629842, 0.7527061 , 0.45410959, 0.55509555],
       [0.61149377, 0.6269457 , 0.81110158, 0.8205821 , 0.77371262]])

In [4]:
# arr is a 25 element Vector
t_arry

array([[0.68604398, 0.48760717, 0.91450232, 0.50920939, 0.55626204],
       [0.03008223, 0.31888678, 0.42574807, 0.26249342, 0.83257085],
       [0.76911744, 0.12980691, 0.41680284, 0.75819428, 0.60237452],
       [0.48123654, 0.59629842, 0.7527061 , 0.45410959, 0.55509555],
       [0.61149377, 0.6269457 , 0.81110158, 0.8205821 , 0.77371262]])

In [7]:
t_arry.shape[1]

5

In [102]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [103]:
arr.reshape(1,25).shape

(1, 25)

In [104]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [106]:
arr.reshape(25,1).shape

(25, 1)

In [107]:
arr.reshape(5,5).shape

(5, 5)

### DTYPE

You can also grab the data type of the object in the array. This an array ATTRIBUTE.

In [111]:
arr.dtype

dtype('int64')

In [121]:
arr2 = np.random.rand(5)
arr2.dtype

dtype('float64')

# Great Job!