___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [6]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
#Get a value at an index
arr[8]

8

In [8]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [9]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast, populating a specific value in the specified slots of the array.

In [13]:
arr[0:5]=100    # Replaces elements between [0] and [4] with the value 100 
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(NB) Slicing arrays references the original array and does not generate a new copy, so as to save memory

In [20]:
#Important notes on Slices 
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [23]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity and less errors.

In [24]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [55]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

### Retrieving sub matrices using array slicing:

In [50]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [51]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [54]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [3]:
#Set up matrix
arr2d = np.zeros((10))
arr2d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#Length of array
arr_length = arr2d.shape[0]
arr_length

10

In [13]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Fancy indexing allows the following

In [14]:
arr2d[[2,4,6,8]]

array([2., 4., 6., 8.])

In [15]:
#Allows in any order
arr2d[[6,4,2,7]]

array([6., 4., 2., 7.])

In [23]:
arrs = np.random.rand(3,3)
arrs

array([[0.9747111 , 0.77500594, 0.15728853],
       [0.12984955, 0.10817903, 0.49135276],
       [0.60257568, 0.05649769, 0.78031921]])

In [32]:
arrs[1,:2]

array([0.12984955, 0.10817903])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [33]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr>4

In [36]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr2d = np.arange(50).reshape(5,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
arr2d[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

# Great Job!
